### ISSUE TITLE
Prod - Installation Module oiseau sene

### ISSUE THREAD

**Issue by pierre56** [Bretagne-Vivante/protocoles_suivi#12]
# Mise en prod du module oiseau d'eau

pas mal de prérequis

## Tickets associés
#3 
#11 
#4 
#10 

## A Faire

- [x] Creation compte utilisateurs
- [x] Création liste utilisateurs
- [ ] Création CA 
- [ ] Création JDD
- [x] Création de la liste des taxons
- [x] Ajout des taxons à la liste des taxons
- [ ] Ajout des référentiels geo
- [ ] Installation du module oiseau dans monitoring
- [ ] Ajout des sites au bon module
- [ ] Test du module par les utilisateurs
- [ ] Validation du module

## version

monitoring 0.2.6 - a jour
geonature 2.7.5 - a jour

**Comment by pierre56** [comment]
# Création de la liste des taxons
Erreur lors de l'enregistrement

## LOG

INFO:sqlalchemy.engine.base.Engine:INSERT INTO taxonomie.bib_listes (code_liste, nom_liste, desc_liste, picto, regne, group2_inpn) VALUES (%(code_liste)s, %(nom_liste)s, %(desc_liste)s, %(picto)s, %(regne)s, %(group2_inpn)s) RETURNING taxonomie.bib_listes.id_liste
INFO:sqlalchemy.engine.base.Engine:{'code_liste': 'liste_oiseau_eau', 'nom_liste': "Oiseaux d'eau", 'desc_liste': 'Liste Oiseaux pour WetLands\nTest pour séné', 'picto': 'images/pictos/oiseau.gif', 'regne': 'Animalia', 'group2_inpn': 'Oiseaux'}
INFO:sqlalchemy.engine.base.Engine:ROLLBACK
ERROR:root:(psycopg2.errors.InsufficientPrivilege) ERREUR:  droit refusé pour la séquence bib_listes_id_liste_seq

## SQL


GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA taxonomie TO geonatadmin;

## Liste 

![image](https://user-images.githubusercontent.com/26764293/134305905-218e76a9-4ab4-4d04-800f-c4ef32e07526.png)

**Comment by pierre56** [comment]
# Ajout des taxons dans la liste des taxons

1. Se connecter a taxhub https://taxhub.bretagne-vivante-dev.org/#!/taxref
![image](https://user-images.githubusercontent.com/26764293/134316683-72c2dbe1-d9fe-4faf-b30a-00da075ad602.png)


2. Page taxref, sélectionner le taxon

![image](https://user-images.githubusercontent.com/26764293/134316050-f9be3325-e006-45c2-8858-93e0264067fd.png)
3. Aller sur l'onglet liste

![image](https://user-images.githubusercontent.com/26764293/134316225-5675acd9-182e-4398-80a3-1bbea32b8c27.png)

4. Sélectionner la liste et ajouter via le + , enregistrer
![image](https://user-images.githubusercontent.com/26764293/134316366-3007d12a-30ba-41d4-8a71-d5e5611d3a6b.png)

5. Vérifier la présence dans la liste
![image](https://user-images.githubusercontent.com/26764293/134316632-65ededbf-e4a6-4937-a592-5bcd1e35bd9d.png)

**Comment by pierre56** [comment]
# Ajout du référentiel geo

Voir ticket #4 

- [x] Création d'un nouveau type "secteur ORA" dans bib_areas_types
- [x] Création d'un table li_entites_ora_interne
- [x] insertion des secteurs ora dans ref_geo.l_areas
- [ ] Insert des secteurs ORA dans gn_monitoring.t_base_sites
- [ ] Insert t_bases_sites dans cor_site_module


## SQL

INSERT INTO ref_geo.bib_areas_types
(id_type , type_name, type_code, type_desc, ref_name, ref_version, num_version)
VALUES(35,'Entités ORA', 'ORA', 'Entités de comptages ORA', 'BV_ORA', 2020, '1');

--------------------------

insert into ref_geo.l_areas ( id_type, area_name, area_code, geom, centroid, geojson_4326, "source", "comment", "enable", meta_create_date, meta_update_date, additional_data ) (
Select
35::int as id_type,
nom as area_name,
id_ora as area_code,
geom,
NULL as centroid,
ST_AsGeoJSON(ST_Transform(geom,4326)) as geojson_4326,
'BV Interne' as source,
version as comment,
true as enable,
now() as meta_create_date,
now() as meta_update_date,

 (

select
jsonb_build_object( 
'id_ora',id_ora,
'nom', nom,
'nom_synth',nom_synth ,
'id_synth' ,id_synth,
'nom_wi',nom_wi,
'ensble_om',ensble_om,
'id_ensble',id_ensble, 
'shape_leng',shape_leng,
'shape_area',shape_area,
'nat_id',nat_id,
'local_id',local_id,
'name',"name",
'gci',gci,
'id_hv2',id_hv2,
'id_hv1',id_hv1,
'id_basile',id_basile,
'fid_ii',fid_ii,
'id_orom',id_orom,
'code_geoca',code_geoca,
're_geoca',re_geoca,
'info',info,
'id_fb',id_fb,
'fb_site_fo',fb_site_fo,
'fb_nat_id',fb_nat_id,
'fb_local_i',fb_local_i,
're_wi',re_wi,
'version',"version",
'date_modif',date_modif,
'motif_modif', motif_modif

)

from ref_geo.li_entites_ora_interne sub
where sub.id_ora = li_entites_ora_interne.id_ora

)::jsonb as additional_data -- a ameliorer mais suffisant pour test

from ref_geo.li_entites_ora_interne
)

--------------------------

**Comment by pierre56** [comment]
# Installation du module oiseau sur server de prod

## voir
#3 

- [x] Ajout du module sur le server
- [x] Installation du module
- [x] Configuration du module


## CMD

cd <path_to_geonature>
source backend/venv/bin/activate

export FLASK_APP=geonature

flask monitorings install /home/geonatureadmin/gn_module_monitoring/contrib/suivi_oiseaux_eau_sene

geonature frontend_build

## error
### log


```
Configuration du module non accéssible (installation en cours)
/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalche                                                                                                             my/orm/mapper.py:1899: SAWarning: Implicitly combining column t_modules.meta_cre                                                                                                             ate_date with column t_module_complements.meta_create_date under attribute 'meta                                                                                                             _create_date'.  Please configure one or more attributes for these same-named col                                                                                                             umns explicitly.
  util.warn(msg)
/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalche                                                                                                             my/orm/mapper.py:1899: SAWarning: Implicitly combining column t_modules.meta_upd                                                                                                             ate_date with column t_module_complements.meta_update_date under attribute 'meta                                                                                                             _update_date'.  Please configure one or more attributes for these same-named col                                                                                                             umns explicitly.





[2021-09-22 01:16:21 +0200] [2690] [INFO] Configuration du module non accéssible (installation en cours)
[2021-09-22 16:36:18 +0200] [4723] [ERROR] Exception on /monitorings/config/suivi_oiseaux_eau_sene [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/config.py", line 22, in get_config_api
    return get_config_frontend(module_code, verification_date=True)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/config/repositories.py", line 237, in get_config_frontend
    config = dict(get_config(module_code, verification_date))
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/config/repositories.py", line 122, in get_config
    base_last_modif = get_base_last_modif(module)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/config/utils.py", line 56, in get_base_last_modif
    return (date_module - datetime.datetime(1970, 1, 1)).total_seconds() - offset
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'
[2021-09-22 16:37:05 +0200] [1591] [ERROR] Exception on /monitorings/config/suivi_oiseaux_eau_sene [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/config.py", line 22, in get_config_api
    return get_config_frontend(module_code, verification_date=True)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/config/repositories.py", line 237, in get_config_frontend
    config = dict(get_config(module_code, verification_date))
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/config/repositories.py", line 122, in get_config
    base_last_modif = get_base_last_modif(module)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/config/utils.py", line 56, in get_base_last_modif
    return (date_module - datetime.datetime(1970, 1, 1)).total_seconds() - offset
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'

```

> il a fallu que je rajoute une date dans la table 
![image](https://user-images.githubusercontent.com/26764293/134367555-951deee1-45a9-41f0-ab72-114139f3b6bd.png)


## Configuration

![image](https://user-images.githubusercontent.com/26764293/134367653-5f301a8f-1ade-4160-8761-4eb3308ee38f.png)

![image](https://user-images.githubusercontent.com/26764293/134369399-d45af5c4-c703-459e-8c57-747eb2fb99e7.png)
